---
- name: Base setup of new server
  hosts: servers
  become: true
  vars_files:
    - vault.yml

  vars:
    motd_debian: "*** labjunkie.org - no unauthorised access ***\n"

  tasks:
    - name: set ssh motd
      copy:
        content: "{{ motd_debian }}"
        dest: /etc/motd
        mode: '0644'
      when: ansible_distribution == "Debian"
      notify: MOTD changed

    - name: update and upgrade packages
      apt:
        upgrade: dist
        update_cache: yes
        force_apt_get: yes
      when: ansible_distribution == "Debian"
      notify: Updated Server

    - name: check if docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: true
      notify: Docker Already Installed

    - name: download docker install script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/getdocker.sh
        mode: '0744'
      when: ansible_distribution == "Debian" and docker_installed.failed
      notify: Docker Script Downloaded

    - name: install docker
      shell: yes | sh /tmp/getdocker.sh
      when: ansible_distribution == "Debian" and docker_installed.failed
      notify: Docker Installed

    - name: check if docker installation script exists
      stat:
        path: /tmp/getdocker.sh
      register: docker_script

    - name: cleanup docker installation script
      ansible.builtin.file:
        path: /tmp/getdocker.sh
        state: absent
      notify: Docker Script Removed
      when: ansible_distribution == "Debian" and docker_script.stat.exists

  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD was changed on {{ hostvars[inventory_hostname]['ansible_hostname'] }}
    - name: Updated Server
      debug:
        msg: Packages were updated
    - name: Docker Script Downloaded
      debug:
        msg: Docker script downloaded
    - name: Docker Installed
      debug:
        msg: Docker installed
    - name: Docker Script Removed
      debug:
        msg: Docker installation script removed
    - name: Docker Already Installed
      debug:
        msg: Docker already installed
...