---
- name: Setup initial user
  hosts: servers
  become: true
  vars_files:
    - vault.yml

  tasks:
    - name: Ensure .ssh directory exists for initial user
      file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'

    - name: Copy the public key to the initial users authorized_keys
      copy:
        src: "/home/{{ ansible_user }}/keys/super.pub"
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      notify: copy initial pub

    - name: Disable password authentication for SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: disable password auth

    - name: Reload SSH service to apply changes
      service:
        name: sshd
        state: reloaded
      notify: reload sshd

  handlers:
    - name: copy initial pub
      debug:
        msg: initial user public key copied to {{ hostvars[inventory_hostname]['ansible_hostname'] }}
    - name: disable password auth
      debug:
        msg: password authentication disabled for initial user on {{ hostvars[inventory_hostname]['ansible_hostname'] }}
    - name: reload sshd
      debug:
        msg: sshd service reloaded on {{ hostvars[inventory_hostname]['ansible_hostname'] }}

- name: Setup ansible user on servers
  hosts: servers
  become: true
  vars_files:
    - vault.yml

  tasks:
    - name: Check if ansible user exists
      getent:
        database: passwd
        key: ansible
      register: ansible_user_exists
      ignore_errors: true

    - name: Create ansible user if not present
      user:
        name: ansible
        comment: "Ansible User"
        shell: /bin/bash
        create_home: true
        state: present
      when: ansible_user_exists is failed
      notify: ansible user created

    - name: Create .ssh directory
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'
      notify: created ssh dir

    - name: Copy the existing public key to the managed nodes
      copy:
        src: "{{ ansible_pub }}"
        dest: /home/ansible/.ssh/authorized_keys
        owner: ansible
        group: ansible
        mode: '0600'
      notify: copy ansible public

    - name: Ensure ansible user can use sudo without password
      lineinfile:
        path: /etc/sudoers.d/ansible
        state: present
        create: true
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        mode: '0440'
      notify: sudoers

  handlers:
    - name: ansible user created
      debug:
        msg: ansible user created on {{ hostvars[inventory_hostname]['ansible_hostname'] }}
    - name: created ssh dir
      debug:
        msg: created ansible ssh dir on {{ hostvars[inventory_hostname]['ansible_hostname'] }}
    - name: copy ansible public
      debug:
        msg: copied ansible public key to {{ hostvars[inventory_hostname]['ansible_hostname'] }}
    - name: created ssh dir
      debug:
        msg: created ansible ssh dir on {{ hostvars[inventory_hostname]['ansible_hostname'] }}
    - name: sudoers
      debug:
        msg: ansible user added to sudoers {{ hostvars[inventory_hostname]['ansible_hostname'] }}
